eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
    ip: 192.168.1.205

login:
    url:
        path: /users/login

server:
    port: ${PORT:0}

spring:
    application:
        name: users-ws
    datasource:
        password: root
        testWhileIdle: true
        url: jdbc:mysql://localhost:3306/photoapp?useSSL=false
        username: root
        validationQuery: SELECT 1
    devtools:
        restart:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true

token:
    expiration_time: 86400000000
    secret: hfgry463hf746hf573ydh475fhy5739
